# -*- coding: utf-8 -*-
"""Biologia Genetica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PWIpZ4rzH3h4ix9idUOpMeMKCexY5oCj
"""

from google.colab import files
uploaded = files.upload()

# ================= LIBRERIE =================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from scipy import stats
import io

# ================= LETTURA CSV =================
df = pd.read_csv(io.BytesIO(uploaded['genetica.csv']))

print(df.head())

# ================= STATISTICA DESCRITTIVA =================
print("\n=== STATISTICA DESCRITTIVA ===")
print(df.describe())

# ================= REGRESSIONE LINEARE SEMPLICE =================
X = df[['Frequenza_Allele_Dominante']]
y = df['Percentuale_Fenotipo_Dominante']

model = LinearRegression()
model.fit(X, y)

print("\n=== REGRESSIONE SEMPLICE ===")
print(f"Intercetta: {model.intercept_:.4f}")
print(f"Coefficiente: {model.coef_[0]:.4f}")
print(f"R²: {model.score(X, y):.4f}")

# ================= GRAFICO REGRESSIONE =================
plt.figure(figsize=(8,6))

plt.scatter(
    df['Frequenza_Allele_Dominante'],
    df['Percentuale_Fenotipo_Dominante'],
    color='blue',
    label='Dati osservati'
)

plt.plot(
    df['Frequenza_Allele_Dominante'],
    model.predict(X),
    color='red',
    linewidth=3,
    label='Retta di regressione'
)

plt.xlabel('Frequenza Allele Dominante')
plt.ylabel('Percentuale Fenotipo Dominante')
plt.title('Relazione tra Allele Dominante e Fenotipo')
plt.legend()

plt.grid(True)
plt.show()

# ================= CREAZIONE VARIABILI CATEGORICHE =================
df_encoded = pd.get_dummies(
    df,
    columns=['Generazione', 'Tipo_Ereditarieta'],
    drop_first=True
)

print(df_encoded.head())

# ================= REGRESSIONE MULTIPLA =================
X_multi = df_encoded.drop(
    'Percentuale_Fenotipo_Dominante',
    axis=1
)

y_multi = df_encoded[
    'Percentuale_Fenotipo_Dominante'
]

model_multi = LinearRegression()
model_multi.fit(X_multi, y_multi)

print("\n=== REGRESSIONE MULTIPLA ===")

for nome, coef in zip(
        X_multi.columns,
        model_multi.coef_):
    print(f"{nome}: {coef:.4f}")

print(f"\nIntercetta: {model_multi.intercept_:.4f}")
print(f"R² complessivo: {model_multi.score(X_multi, y_multi):.4f}")

# ================= BOXPLOT AMBIENTE =================
plt.figure(figsize=(8,6))

sns.boxplot(
    x='Presenza_Ambientale',
    y='Percentuale_Fenotipo_Dominante',
    data=df,
    palette=['lightgreen','salmon']
)

plt.xticks(
    [0,1],
    ['Condizioni Ideali','Stress Ambientale']
)

plt.title('Fenotipo Dominante e Ambiente')
plt.xlabel('Condizioni Ambientali')
plt.ylabel('Percentuale Fenotipo Dominante')

plt.grid(True, alpha=0.3)
plt.show()

# ================= T-TEST =================
gruppo0 = df[
    df['Presenza_Ambientale'] == 0
]['Percentuale_Fenotipo_Dominante']

gruppo1 = df[
    df['Presenza_Ambientale'] == 1
]['Percentuale_Fenotipo_Dominante']

t_stat, p_value = stats.ttest_ind(
    gruppo0,
    gruppo1
)

print("\n=== T-TEST ===")
print(f"Media condizioni ideali: {gruppo0.mean():.2f}")
print(f"Media stress ambientale: {gruppo1.mean():.2f}")
print(f"t-statistic: {t_stat:.4f}")
print(f"p-value: {p_value:.5f}")

if p_value < 0.05:
    print("Differenza statisticamente significativa")
else:
    print("Differenza NON significativa")

# ================= GRAFICO EREDITARIETA =================
plt.figure(figsize=(8,6))

sns.boxplot(
    x='Tipo_Ereditarieta',
    y='Percentuale_Fenotipo_Dominante',
    data=df,
    palette='Set2'
)

plt.title('Fenotipo dominante nei diversi tipi di ereditarietà')
plt.xlabel('Tipo di ereditarietà')
plt.ylabel('Percentuale Fenotipo Dominante')

plt.grid(True, alpha=0.3)
plt.show()

# ================= ISTOGRAMMA =================
plt.figure(figsize=(8,6))

sns.histplot(
    df['Percentuale_Fenotipo_Dominante'],
    bins=10,
    kde=True,
    color='green'
)

plt.title('Distribuzione del Fenotipo Dominante')
plt.xlabel('Percentuale Fenotipo Dominante')
plt.ylabel('Frequenza')

plt.show()